#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "Please set the PYFILE environment variable."
    exit 1
fi

echo "Compiling $PYFILE ..."
python3 -c "import py_compile; py_compile.compile('$PYFILE', '$PYFILE"c"')"
